[package]
name = "tomato"
version = "0.1.0"
edition = "2021"
authors = ["kgagag@163.com"]  # 添加这一行

[dependencies]
lazy_static = "1.4"
clap = "4.4.6"
byteorder = "1.4"
log = "0.4"
env_logger = "0.11.3"
zip = "2.1.3"
tiny_http = "0.8.0" 
dashmap = "5.5"
linked-hash-map = "0.5.6"